# Generated by Django 5.0.1 on 2024-01-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_az',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_az', to='shopAviato.category', verbose_name='Категория (АЗ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_ru', to='shopAviato.category', verbose_name='Категория (РУ)'),
        ),
    ]
