# Generated by Django 5.0.1 on 2024-02-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trading',
            new_name='trending',
        ),
    ]
