# Generated by Django 5.0.1 on 2024-01-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0002_remove_product_category_product_category_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopAviato.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_az',
            field=models.CharField(default='', max_length=200, verbose_name='Название категории (АЗ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Название категории (РУ)'),
        ),
    ]
