# Generated by Django 5.0.1 on 2024-02-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0002_rename_trading_product_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
