# Generated by Django 5.0.1 on 2024-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0003_alter_category_options_remove_product_category_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trading',
            field=models.BooleanField(default=False, verbose_name='В тренде'),
        ),
    ]
