# Generated by Django 5.0.1 on 2024-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0004_alter_product_sale_alter_product_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(default=0.0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trading',
            field=models.BooleanField(default=False),
        ),
    ]
