# Generated by Django 5.0.1 on 2024-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0005_alter_product_sale_alter_product_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trading',
            field=models.BooleanField(default=False, verbose_name='В тренде'),
        ),
    ]
