# Generated by Django 5.0.1 on 2024-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0006_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
