# Generated by Django 5.0.1 on 2024-02-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0007_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
