# Generated by Django 5.0.1 on 2024-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0009_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
