# Generated by Django 5.0.1 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.TextField(default=''),
        ),
    ]
