# Generated by Django 5.0.1 on 2024-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAviato', '0012_purchuase_purchuasequntity_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=1000)),
                ('contacts', models.TextField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
